services:
  - type: web
    name: moviemandap-backend
    env: node
    plan: free
    rootDir: .
    buildCommand: yarn install && yarn build:backend:prod
    startCommand: node apps/backend/dist/main.js
    healthCheckPath: /graphql
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: JWT_SECRETE
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: SENDER_EMAIL
        sync: false
      - key: CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: CLOUDINARY_URL
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
